### ISSUE TITLE
Cant get it to work with 3mf files

### ISSUE THREAD

**Issue by mix579** [DavidPhillipOster/ThumbHost3mf#3]
Installed per instructions on Sonoma 14.1.2. Works great with gcode and bgcode files but can't get it to show 3mf files. Attached is a simple cube, directly saved from PS 2.7.0. 
[test.3mf.zip](https://github.com/DavidPhillipOster/ThumbHost3mf/files/13653981/test.3mf.zip)

I tried Open With but ThumbMF3 is grayed out and cannot be selected.

**Comment by DavidPhillipOster** [comment]
How frustrating!: As soon as I told Finder to uncompress test.3mf.zip, the uncompressed file had the preview icon for me, and when I used the Open command in ThumbMF3, it showed the correct preview icon.

You wrote:

> I tried Open With but ThumbMF3 is grayed out and cannot be selected.

that means the launch services database has not been updated with the information from ThumbMF3.

I've seen this before, with a different app: https://github.com/MaddTheSane/Simple-Comic/issues/57

Do this: 

* copy ThumbMF3 into /Applications or a sub directory of  /Applications. Delete any other copies of ThumbMF3.
* restart your Mac, so that the Finder process has to do a full re-initialization from its beginning.
* Run ThumbMF3, and using its **File** > **Open** command, open a .3MF file.
* Quit ThumbMF3
* restart your Mac a second time.

Now, the LaunchServices database and the Quicklook database should be updated to recognize that ThumbMF3 can open .3MF files, and the that the finder should use ThumbMF3’s embedded QuickLook plugin to generate Finder icons.

Please let me know by replying to this issue if that solves your problem. If it does, I'll modify the ReadMe file with the revised installation instructions.

**Comment by mix579** [comment]
I got it to work! The issue was that I had moved it to ~/Applications. When I quit the app, moved it to /Applications, and restarted it, it began to recognize 3mf files. No reboot necessary. Probably worth adding that to the Readme file.

Thanks for this nice utility app!
