### ISSUE TITLE
Thumbnails not working in Finder search results

### ISSUE THREAD

**Issue by markcarroll** [DavidPhillipOster/ThumbHost3mf#8]
Firstly, thank you for an awesome tool. Just what I was looking for.  

Unfortunately there is one issue that I have found.  While this does show the thumbnails in regular Finder views, it does not show them in the Finder search results.  Instead, all I have there is the "zip" icon.  

Reproduce:

1. Go to Finder. 
2. In search bar type `3mf` and click on "name contains"
3. See results only show zip file icon

**Comment by DavidPhillipOster** [comment]
This is going to be difficult to fix, since I can't reproduce it on my mac.

![Screenshot 2024-05-26 at 9 23 47 AM](https://github.com/DavidPhillipOster/ThumbHost3mf/assets/5148308/8477b140-de5b-4ad8-ac5a-a39db0516615)

The .zip icon means that some app has an Info.plist that provides a UTI (Uniform Type Identifier) that says that the .3mf file extension means that the file is a kind of zip file. That's true, but it also means that some app is providing information about the file extension. Odd that Finder is looking up its action one way for normal windows and a different way for search result windows.

**Comment by markcarroll** [comment]
Try switching to icon view. See what you get then.   

And yes, I agree it is odd.

**Comment by DavidPhillipOster** [comment]
![iconMode](https://github.com/DavidPhillipOster/ThumbHost3mf/assets/5148308/b5fa1771-c004-4897-9031-547ef2eebd65)

Note that my thumbnailer only reads the thumbnails that the app that wrote the .3mf put into the .3mf. My thumbnailer doesn't interpret the 3d model itself. The files for the Prusa 2.5 are from before Prusa wrote embedded thumbnails into the files.

**Comment by markcarroll** [comment]
Closing this as it seems to work after a reboot.  I also changed the default for 3MF files from OrcaSlicer to Bambu Studio.  Not sure if that helped.   

Thanks for looking and for the awesome tool.
